### PR TITLE
Set page style as empty in assign pages and fix underline long text.

### PR DESCRIPTION
**Pull request by sighingnow**
+ Set page style as empty before start assign pages and restore after announce page.
+ Use `\uline` command to underscore long text, use `\hfill` to fill the last line and make next line manually.
+ The custom `\ulinel` command will be used to create empty underscored lines only.

### CODE REVIEW

**Comment by sighingnow** [comment]
Ping @huxuan 

This pull request solves the issue #189, about underscoring long text in bachelor's thesis.

**Comment by huxuan** [comment]
Sorry for the delay. This PR is a little bit longer and I would like to have a more detailed review. Suppose to finish today or tomorrow, and feel free to ping me if there is no progress then.

**Comment by sighingnow** [comment]
When I investigate issue #195, I find that the `\uline` provided by `ulem` package doesn't support automatic break-line for English text defined by `\newcommand` and I can't find any related information in it's documentation. A minimal example to reproduce this trouble:

~~~latex
\documentclass{article}
\usepackage{ulem}

\newcommand{\longtext}{Long text Long text Long text Long text
                       Long text Long text Long text Long text
                       Long text Long text Long text Long text
                       Long text Long text Long text Long text}

\begin{document}
\uline{\longtext}
\end{document}
~~~

I don't know why the previous solution works well for long Chinese text! I seems that the order of macro expanding does matter. And it may be related to how ctex handle Chinese text.

After some attempts, it can be solve by `\useunder` command from `ulem` package. I redefine previous `\ulinel` command, and rename the old definition as `ulineblank` (which can be used to create an empty underscored line). 

Besides, the latest commit has cleaned some unnecessary long text examples to make the diff of this pull request more clear.

**Comment by huxuan** [comment]
From user's perspective, break the line manually may be a little ugly, but it works for having a fixed style of corresponding part. It means even when we have just a little or even no content, they should still occupy same number of lines. Your changes seem to solve the underlined long text problem, but I do not think it fits our scenario very well. WDYT, @JosephPeng?

**Comment by sighingnow** [comment]
Indeed, I also strongly support of the idea that we should have a fixed style in these two pages and every part should occupy same lines whether there is enough contents. That's why I leave the `\ulineblank` command to create empty lines.

This pull request will lead that user needs to modify the `.cls` file directly to keep to fixed style. I admit it may cause some troubles to ordinary users. In my personal opinion, I support the idea that "this is more like a feature than a bug" and I also don't like the solution in this pull request......

Another more practical solution is keeping the assign pages as it is and also providing the new version `ulinel` command for advance users, as well as necessary documentation to address these issue.

**Comment by huxuan** [comment]
Yep, thanks for your consideration. It is OK to provide new underline command with necessary document. Maybe we should also add some document about the assignment page "bug".

In my opinion, it is always not a good idea to let user modify the `cls` file cause most of them do not know what they are doing and it will make it even harder when they encounter other problems which we may not be able to reproduce.

For this PR, I would suggest it only focus on the page style correction. We may need more discussion about the underline implementation.

**Comment by huxuan** [comment]
Close as discussed.

**Pull request closed without merging**
