### PR TITLE
硕士题名页的格式修改

### PR DESCRIPTION
**Pull request by iEverX**

### CODE REVIEW

**Comment by sighingnow** [comment]
Thanks, I will check our requirement as soon as possible.

**Comment by JosephPeng** [comment]
Hi, @iEverX 
Could you please provide the output screenshot of the modifies you are pulling, thanks.
And, in the prototype of this cls, many adjusts and tricks have been used for matching the official template .

**Comment by sighingnow** [comment]
This patch looks good for me.

This style is master's thesis only. I approve this pull request for it's better satisfaction with the official requirement, although users with current style are not rejected when submit their papers.

Currently this page looks as

image

After apply this patch, it looks as

image

**Comment by sighingnow** [comment]
(The size of these two screenshots may cause some concerns, in fact this patch didn't affect the font size and margins, the only different is the number of whitespaces between some texts.)

**Comment by huxuan** [comment]
Thanks for bettering BUAAthesis. @iEverX 
Thanks for the confirmation. @sighingnow

**Pull request merged**
