### PR TITLE
add footnote capability for table environment

### PR DESCRIPTION
**Pull request by jmaximelv**
use \tablefootnote{*****} can add footnote in the table environment, but the hyperlink not work

### CODE REVIEW

**Comment by huxuan** [comment]
The diff looks pretty good for me, but there seems to have some small problems.

1. Where to place `\RequirePackage{tablefootnote}`

   There is a section begin with `%%%%%%%%%% table %%%%%%%%%%` and I think that's where we should put table related code there.

1. The code doesn't seem to work out as expected, I have add a screenshot with difference pointed out. If I happened to make some mistake, feel free to tell me.
image

**Comment by jmaximelv** [comment]
Yep, for the first problem, \RequirePackage{tablefootnote} should be put in the "table" section.
For the second problem, you mean the footnote should be a letter rather than a number?  I've check the package use manual, it seems that you can use any number or some others "footnote-symbol" like "\dag" or "\ddag" by "\renewcommand{\thefootnote}{\arabic{footnote}}", but it seems it cannot use letter as a tag.

Bests,

**Comment by huxuan** [comment]
Hi @jmaximelv ,

I am not mean the footnote marker style, but the way show the footnote. In the original version, the footnote comes directly after the table rather than the bottom of the page. That's the case the document want to describe. They seems to be different ones.

**Comment by jmaximelv** [comment]
Sorry for the mistake! I've thought the footnote should be in the "foot" of the page. I don't know how to move it just below the table.

Bests,

**Comment by huxuan** [comment]
@jmaximelv Yep, in that way, this should not be the replacement but enhancement. I would suggest you to add related snippets after that section. Then it would be a good PR and I would be proud to merge it.

**Comment by JosephPeng** [comment]
Hi, @jmaximelv , as @huxuan says, the footnote of 'table' settled at the end( or foot) of a 'page' might not be a proper solution. 
It is recommended to make the different method of "the footnote of a table" as an option(what I mean is two different 'environment' in the cls) for user.
It will be appreciated if you pull a new request for the optional table footnote.
Otherwise, feel free to connect us when there are some problems while using this cls.

**Pull request closed without merging**
