### PR TITLE
Fix deprecated options and commands of the ctex package

### PR DESCRIPTION
**Pull request by sighingnow**
Fix some deprecated options and commands of the ctex package in the file buaathesis.cls. Texlive 2015  with ctex v2.0.2 has been tested(the latest release of ctex is v2.4.4).

### CODE REVIEW

**Comment by huxuan** [comment]
Cool! Thanks for the contribution! The changes looks good to me. @JosephPeng do you have any comments?

**Comment by JosephPeng** [comment]
@huxuan 
@sighingnow ’s PR seems brilliant, many thanks for @sighingnow ’s contribution.
However, the compatibility of the old ctex package version should be concerned too. This PR will be acceptable(in my opinion) as if you have made sure about the previous ctex version.
Hoping for your further advices.

**Comment by sighingnow** [comment]
Thanks for your reply @huxuan @JosephPeng .
These changes are all imported from release v2.0 and it was published at 2015. I afraid that this patch may not work as expected with previous tex suites, for example, Texlive 2014. This PR should be closed.

**Comment by huxuan** [comment]
As we do not suppose who will use this template for more than one time. I think it is OK to only support new packages. I will reopen this PR, if @JosephPeng have no further comments, I will merge it in one or two days.

**Comment by JosephPeng** [comment]
Hi, @huxuan 
OK, I can accept that.
Besides, this changes should be mentioned in somewhere, I wish @sighinhnow could make another PR for the ctex version update in document or Readme.md, which I think should be modified formally years ago.

**Comment by huxuan** [comment]
Good point. @sighingnow, we need to update corresponding documents together. Would you please take another look?

**Comment by sighingnow** [comment]
I have updated the document about this compatibility issue.

**Comment by huxuan** [comment]
Great contribution! Thanks very much! I will add you to BHOSC org and BUAAthesis maintainer Team right now. Wish you have help maintain BUAAthesis well.

**Comment by sighingnow** [comment]
OK, thank you very much for the acceptance. I will maintain this repository and do necessary modifications to adapt the latest standards of our thesis.

**Pull request merged**
