### PR TITLE
We have noticed overfull in texttt, fixes that by allowing break line after any character.

### PR DESCRIPTION
**Pull request by sighingnow**

### CODE REVIEW

**Comment by sighingnow** [comment]
Politely ping @huxuan @JosephPeng @yangalan123 :)

**Comment by yangalan123** [comment]
Can you please show me the effect of whether it will work? (some snapshots showing before/after?) Just to make sure our understanding of how the problem occurs or looks like and how the fix would work.

**Comment by sighingnow** [comment]
Before this fix (current situation):

image

After this fix:

image

**Comment by yangalan123** [comment]
I truly see what worries me: what if we write some English words at the end of the line? Will we be asked to add the hyphen ("-") to connect characters when we are wrapping the line? Can we then still work based on this fix?

**Comment by yangalan123** [comment]
BTW, if you all do not think that will be a problem. I have no other opinions and you can just merge it.

**Comment by huxuan** [comment]
I have to admit I mostly agree with what @yangalan123 said. Do we have any request to make this change? I did not see any related issues actually. In practice, I usually choose to rearrange the content so as to avoid similar problems.

**Comment by sighingnow** [comment]
After further investigation I found the issue is not about `texttt`, it is about `textbackslash`. The `textbackslash` cannot be recognized as a `hyphen` and every long word after it cannot be split correctly, both inside or outside the `texttt` environment.

As for @yangalan123 's concern, the last english word at the end of line has already been split automatically and a `-` has been inserted at the end of line. But when meets `textbackslash` it doesn't work.

Also, there is no obvious way to get a perfect fix. The `hyphenat` package has defined a `BreakableBackslash` but the original `textbackslash` command cannot be renewed thus we cannot do some hack to fix that. Since the problem is fairly rare, I decide to fix the original problem by just inserting `hyp{}` manually.

**Comment by sighingnow** [comment]
Now it should be ok to merge :)

**Comment by huxuan** [comment]
If I understand correctly, we are handling a common LaTeX problem? Line breaks after `\textbackslash`, right?
If so, will this [1] help us? It simply suggests to use `url` package to handle line breaks problem.

[1] https://tex.stackexchange.com/questions/107196/how-to-typeset-a-backslash-and-get-line-breaks-in-urls

**Comment by sighingnow** [comment]
> If so, will this [1] help us? It simply suggests to use url package to handle line breaks problem.

In fact, in [1] two problems are proposed, one is how to print `\` and the other is how to do line break.

The first is trivial, use `\textbackslash`. For the second, we need to notice that `\texttt` and `\path` is not the same thing. Our `texttt` already do correct line breaking for normal text and add a `-` to the end of line (thus we don't fact the later problem).

Our problem is, the line break doesn't work when the text follows a `\textbackslash` (inside or outside the `texttt`). And we cannot use `\path` (`\path` is the `tt` style of `\url`), because

1. it just break the line, doesn't add the `-` at the end of line. 
2. the long word after `\textbackslash` outside the `texttt` environment doesn't have correct line breaking as well, thus `\path` (or `\url`) won't help.

Then the user has two choice:

1. replace every potential "unbreakable" symbols with "breakable" one from the `hyphenat` package
2. insert `\hyp{}` properly.

I prefer the later since it is more friendly for ordinary users.

**Comment by huxuan** [comment]
Since this only exists in the `usage` chapter, I treat it more like a hack in our documents rather than user guide, so it will not mislead and confuse ordinary users unless they have same scenario.

This is the reason I think it is OK to merge this PR. If I am wrong, please let me know.

**Comment by sighingnow** [comment]
@yangalan123 Do you any further comments on this track?

**Comment by yangalan123** [comment]
Sorry about the late reply, I have no further concerns and I have given my approval.

**Pull request merged**
