### PR TITLE
More bst updates

### PR DESCRIPTION
**Pull request by grissiom**
Some code formating(the reason that the diff is so big) and a commit to fix typos and, especially, issue #115. I have to admit that the bst is totally a mass and I spend a whole day to figure out where the problem is... I think we need to re-write the bst in some proper time.

@JosephPeng , plz test this merge request on you side. It seems to work like a charm on my box. I hope it will work for you as well.

### CODE REVIEW

**Comment by ifduyue** [comment]
ping @JosephPeng

**Comment by JosephPeng** [comment]
Hi, @ifduyue 
Sorry for my absent, I've been busy working(actually is moving blocks) those days....

**Comment by ifduyue** [comment]
No problem. Work comes first. :)

**Comment by sighingnow** [comment]
我查看了这个pull request中的几次commit，主要的代码变更来源于将bst文件的缩进调整为两个空格，以及增加了额外的bibtex示例。

对于bst文件，我觉得没有必要因为缩进问题引入如此大的变动（以后出问题不方便blame），另外，@grissiom 我觉得	d6c11c9 中对`@incollection`类型文献的处理仍然有些问题，我的理解是当文集的editor时，“文献题名”和“论文集名”之间依然需要使用`//`分隔，你觉得呢？

@JosephPeng @huxuan 你们觉得呢？如果没什么问题的话，我考虑过两天关掉这个pull request，并着手修复对`@incollection`类型文献的处理。之后如果有新的讨论，再reopen。

**Comment by huxuan** [comment]
这个 PR 可以先留着，不影响提交新 PR 的。等 Merge 了新 PR，这个 conflict 之后应该就算自然淘汰了。

**Comment by sighingnow** [comment]
好的

**Comment by huxuan** [comment]
Finally, I think we can close this pull request, which has accomplished its mission.
Thanks for all the involved people who make BUAAthesis better.

**Pull request closed without merging**
