### PR TITLE
1. 加入buaathesis.bst文件，解决“居然连bst的参考文献样式都木有！闹哪样！”报错。2. 修改\verb用法，解决TexLive 2021编译报错。

### PR DESCRIPTION
**Pull request by Chen-Jie-EE**
1. 加入buaathesis.bst文件，解决“居然连bst的参考文献样式都木有！闹哪样！”报错。
2. 修改\verb用法，解决TexLive 2021编译报错。

### CODE REVIEW

**Comment by huxuan** [comment]
1. Better to split the changes into two separate MR.
2. I do not think we need to specify `buaathesis.bst` here. You can refer to this MR #255 for more information.

**Comment by sighingnow** [comment]
Hi @Chen-Jie-EE,

Thanks for the PR.

+ The `buaathesis.bst` was replaced by `gbt7714`.
+ The fix for `\verb` for TexLive2021 looks good to me, and if could be merged after it in a seperated PR.

**Comment by sighingnow** [comment]
Close as the `\verb` part patch has been cherry-picked as #266.

**Comment by sighingnow** [comment]
I can see why users complain about "居然连bst的参考文献样式都木有！...". We didn't update msmake.bat and which requires buaathesis.bst...

Thanks for reporting that @Chen-Jie-EE and patch is coming...

**Pull request closed without merging**
