### PR TITLE
目录要求小二号黑体加粗

### PR DESCRIPTION
**Pull request by iEverX**

### CODE REVIEW

**Comment by JosephPeng** [comment]
Please verify the requirements of the offical template.
Thanks.

**Comment by sighingnow** [comment]
Hi, Sean, Joseph and iEverX,

I have checked our bachelor's thesis tutorial and found no related information about of the title "目录", "插图目录" and "表格目录", but the example page does use bold font.

Thought I haven't check the official requirement of master's thesis, this patch looks good for me and I agree to merge it into our repo.

**Comment by sighingnow** [comment]
OK, now I will merge. @iEverX thanks for your contribution!

**Comment by JosephPeng** [comment]
Hi, @sighingnow , the following website might have the requirements for Master's thesis, a reverification is needed, I suppose.
And, @iEverX ,thanks for your contribution.

http://graduate.buaa.edu.cn/ch/xuewei/index.jhtml

**Comment by sighingnow** [comment]
OK, I will verify the requirement of master's thesis as soon as possible.

**Comment by sighingnow** [comment]
In the requirement of master's thesis, I found no concrete standard about the fonts of "目录", but a suggestions in the example content page:

> 建议：“目录”字样用小二号黑体加粗

So I think it's ok for us to accept this patch.

**Comment by JosephPeng** [comment]
Hi, @sighingnow 
Thanks for your patient work.

**Pull request merged**
