### PR TITLE
try to fix footer-too-narrow problem (issue #204)

### PR DESCRIPTION
**Pull request by yangalan123**
尝试解决issue #204 ，其实关于个人致谢页，我们学院是要求有页眉的，这个的话我也有办法，基本上就是把cls文件里的个人致谢的部分的thispagestyle从empty改成fancy，但考虑到这可能只是我们学院的要求，这次就不PR了

### CODE REVIEW

**Comment by Somedaywilldo** [comment]
感谢，我看一下，其实考虑学院要求不同，可以考虑更新到README里面，变成一个可选项。

**Comment by huxuan** [comment]
@Somedaywilldo Yihang，你说的学院要求不同，指的是个人致谢的页眉还是页边距问题，如果只是页眉的话，那这个 pr 是不是还是可以 merge 进来的？确认一下理解哈~

**Comment by yangalan123** [comment]
我说的这个学院有关的问题是关于个人声明页的页眉的，和页边距无关，相当于说我发现别的问题我也找到了对应的解决方案，另外这个先别merge，我发现任务书中为了保持排版有一些hardcode，在新的边距设定下会导致任务书中间有大页空白，我会考虑再搞一个更新的PR解决

**Comment by yangalan123** [comment]
[sample-bachelor.pdf](https://github.com/BHOSC/BUAAthesis/files/3255683/sample-bachelor.pdf)
不行...我现在碰到一个问题，来自于任务书参考文献的定义方式，最多只能定义9行？我原来是希望定多一些这样显得任务书最后一页不会太空，上面是我现在改的一个效果，你们如果觉得这样也行我就再搞个新的PR

**Comment by huxuan** [comment]
@yangalan123 任务书那种格式之前实现的时候就没找到好的解决方案，所以确实是 hard code 的，感觉是因为页边距变化把内容挤到下一页了吧，只能权衡一下少放一些内容？

**Comment by yangalan123** [comment]
额如果觉得缩内容更好的话也行，可以看看这个效果：
[sample-bachelor.pdf](https://github.com/BHOSC/BUAAthesis/files/3255740/sample-bachelor.pdf)，如果可以的话我就直接commit了

**Comment by huxuan** [comment]
我觉得挺好的，删内容应该比加内容容易…… 可以先交上来试试 @sighingnow 现在是不是也毕业了？可以让其他人也看看~

**Comment by yangalan123** [comment]
新的任务书已经commit，如果contributor觉得没问题就可以合并了，最近的一版导出的PDF：
[sample-bachelor.pdf](https://github.com/BHOSC/BUAAthesis/files/3255880/sample-bachelor.pdf)

**Comment by huxuan** [comment]
@yangalan123 Looks Good To Me. @sighingnow please help to double check and feel free to merge.

**Comment by sighingnow** [comment]
@yangalan123 Thanks for diagnosing the issue. I think you could delete those lines you comment out. The `includefoot` part looks reasonable. I will confirm after local validation tonight.

**Comment by sighingnow** [comment]
The `includefoot` part is OK. I remember I have tried to debug this problem about 1 year ago and thanks for your work! @yangalan123 

I have edited this pull request by pushing another commit to minimize the necessary changes. Just not including those lines to the content should be enough and it is ok to keep the definitions like "参考文献第七行". For more information about the hard-code design of "assign page", see also #191 .

I'm going to land this excellent PR!

**Comment by huxuan** [comment]
@yangalan123 Thanks for your contribution. Are you interested in helping maintain BUAAthesis? If so, please feel free to contact us. (Sorry for spamming this issue since I failed to find contact information.)

**Comment by yangalan123** [comment]
Well, I am not sure whether I have enough time for this project. If a part-time and unregular work schedule is acceptable, I am glad to become a contributor. Really thanks for your invitation.

**Comment by sighingnow** [comment]
Welcome! @yangalan123 :clap::clap:

**Comment by huxuan** [comment]
@yangalan123, that is totally fine. As you may known, some of us have graduated from BUAA for nearly 7 years, no one is working on this as full-time job. :-)

**Pull request merged**
