### PR TITLE
add 开题报告 and 文献综述 in buaathesis.cls, marked as ktreport

### PR DESCRIPTION
**Pull request by AlienMarkWong**
在buaathesis.cls中添加了开题报告和文献综述格式的支持，并可以自定义适用于本科生、研究生和博士生。

### CODE REVIEW

**Comment by sighingnow** [comment]
It would be greatly helpful if someone could pick this ticket up and validate if it works (as expected, and as required) ...

**Comment by HansBug** [comment]
Well, gentlemen @AlienMarkWong @sighingnow , I have just tested the code of this PR, it can run properly in the windows (git bash, not cmd) environment.

Some errors ocurred when run it in ubuntu 18, but most of them are something like "font-not-found", it is okay I think (actually when I need to build latex pdf with CI, I need to use an image which contains plenty of fonts and language packages).

以及我们这边要开题报告了，我打算看情况把这个给融了，现在和`master`有冲突，得处理一下，就酱。

**Comment by HansBug** [comment]
Emmm, it is hard to merge actually.

So I push the newest version which support KAI-TI-BAO-GAO to my fork repo, you can use that: https://github.com/HansBug/BUAAthesis/tree/kaiti .

BTW，看了下 #269 ，这真的不能说是没需求啊，问了一圈周围的人愣是找不到一个latex版本开题报告，挺尴尬的。

**Comment by sighingnow** [comment]
> 

It's great to see such an effort! Could you please submit a PR and update the readme for a short guidance about 开题报告？

We can merge it to this repo to help more people.

**Comment by sighingnow** [comment]
Looks like your work is based on this PR, but I guess @AlienMarkWong may don't have enough bandwidth to revisit this PR. Could  you please submit a new PR from your fork instead?

It's OK to me for merging.

**Comment by HansBug** [comment]
To be continued~~~ #287

**Comment by sighingnow** [comment]
Close as merged in #287.

**Pull request closed without merging**
